### ISSUE TITLE
Chips M1 ou M2 da apple

### ISSUE THREAD

**Issue by dleomil** [devfullcycle/fc-devops-docker#1]
No arquivo do docker-compose.yaml é necessário adicionar a tag abaixo na criação de algumas imagens como a utilizada no curso (mysql:5.7).

platform: linux/amd64

db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    platform: linux/amd64
    container_name: db
    restart: always
    tty: true

**Comment by argentinaluiz** [comment]
Olá @dleomil (Daniel), tudo bem?

Você pode criar um arquivo na raiz do projeto chamado de `docker-compose.override.yaml` com o seguinte conteúdo:
```yaml
version: '3'

     meu-banco: # colocar o mesmo nome que está no docker-compose.yaml
          platform: linux/amd64
```

Quando o `docker compose up` for executado, o Docker Compose mescla as configurações nos 2 arquivos, isto ajuda a não afetar o arquivo principal, uma vez que esta necessidade é do MAC, podemos não fazer commit no Git deste override, entendeu a ideia?

;)
